# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23605d50227ea4e00345d4487aa9459f13b51642d6f9edecf4fee60e08a622577de37bcfcd347efd83185c4dc7b975b0168f3f9afa60c9719829955a059577bd

test:
  secret_key_base: 227759beb9c75e695848622396a168b0ec2d7257fa99e1fd6a84966948998a794fa13435aef783e75e7e3c2c0989304d7d7773f322c0426fb60f81db53d1f2c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
